stages:
  - test
  - qa

backend-test:
  stage: test
  image: golang:latest
  tags:
    - aws
    - linux
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cd backend
    - go test -v ./... -count=1

backend-qodana:
  image:
    name: jetbrains/qodana-go:latest
    entrypoint: [""]
  tags:
    - aws
    - linux
  cache:
    - key: qodana-2023.2-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2023.2-$CI_DEFAULT_BRANCH-
        - qodana-2023.2-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - cp qodana-backend.yaml qodana.yaml
    - qodana --cache-dir=$CI_PROJECT_DIR/.qodana/cache  --source-directory=backend --baseline=qodana-backend.sarif.json

frontend-test:
  stage: test
  image: node:latest
  tags:
    - aws
    - linux
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cd frontend
    - npm install --progress=false
    - npm run test:unit

frontend-qodana:
  image:
    name: jetbrains/qodana-js:latest
    entrypoint: [""]
  tags:
    - aws
    - linux
  cache:
    - key: qodana-2023.2-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2023.2-$CI_DEFAULT_BRANCH-
        - qodana-2023.2-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - cp qodana-frontend.yaml qodana.yaml
    - qodana --cache-dir=$CI_PROJECT_DIR/.qodana/cache --source-directory=frontend --baseline=qodana-frontend.sarif.json