# .air.toml
root = "."
tmp_dir = "tmp"
[screen]
  clear_on_rebuild = true
  keep_scroll = true
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]